[workspace]
resolver = "2"
members = [
  "contracts/*",
]

[workspace.dependencies]
soroban-sdk = "21.7.6"
soroban-fixed-point-math = "1.2.0"
tiny-keccak = { version = "2.0.2" }
hex = "0.4.3"
ed25519-dalek = { version = "1.0.1" }
stellar-strkey = { version = "0.0.11" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
