[DOCUMENTATION]
ORG_NAME = "KALEpail Project"
ORG_LOGO = ""
ORG_GITHUB = "https://github.com/kalepail"
ORG_DESCRIPTION = ""

[[CURRENCIES]]
code = "KALE"
issuer = ""
name = "The Blockchain Superfood"
desc = "A Proof-of-Teamwork Stellar Asset powered by a Soroban Smart Contract."
image = ""